

export enum OrderStatus {

  REVISION = 'REVISION',
  CONFIRMADO = 'CONFIRMADO',
  CANCELADO = 'CANCELADO',
  REPARACION = 'REPARACIÓN',
  FINALIZADO = 'FINALIZADO',
  PAGO = "PAGO",
  RETIRADO = "RETIRADO",
  
}
